# -*- coding: utf-8 -*-
"""1018_上機練習.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L9RsAgiiPObU7M1Dff95tfDkmi85DIz2

Ｑ：讓使用者可輸入多個學生成績和姓名，一位學生須輸入兩科科目（科目Ａ、科目Ｂ）的分數。

程式應包含以下操作：

1.   將學生成績和姓名儲存在一個字典中，其中學生姓名是鍵，成績是值。
2.   使用 itertools 模組中的函式，**算出全班有幾位學生。**
1.   根據每位學生兩科的平均成績作排名，並印出此成績單。
2.   使用 re模組檢查，**學生姓名只能包含字母，成績必須為數字**。
1.   平均成績前六名者可進行抽獎，抽出三名學生可得到禮物。
2.   使用迭代器列印中獎名單。

## **請勿刪除註解及修改配分**
"""

# 請import需要使用的相關套件(10%)

import itertools
import re
import random

# 請依據提示完成程式碼，勿修改變數名稱
def main():
    student_scores = {} # 此為儲存學生姓名與成績的字典
    student_count = 0  # 初始化學生人數為 0

    while True: # (40%)
       # 使用迴圈設定條件使程式能執行或停止
       # 使用 re模組檢查，學生姓名只能包含字母，成績必須為數字
        student_name = input("輸入學生姓名（輸入end則結束輸入成績）： ")
        if student_name == 'end':
            break
        
        if not re.match("^[a-zA-Z]+$", student_name):
            print("學生姓名只能包含英文字母,請重新輸入")
            continue
        
        try:
            subject_a_score = int(input(f"請輸入{student_name}科目A的分數；"))
            subject_b_score = int(input(f"請輸入{student_name}科目B的分數；"))
        except ValueError:
            print("成績必須為數字,請重新輸入")
            
        student_scores[student_name] = (subject_a_score, subject_b_score) 
        student_count += 1
        

    def calculate_average(scores):
        # 定義如何計算平均分數(15%)
        return sum(scores) / len(scores)


    avg_scores = {} # 計算每位學生的平均分數並存進字典中，請自行完成{}內的程式碼

    for student_name, scores in student_scores.items():
        avg_scores[student_name] = calculate_average(scores)
        
    print("學生成績單：")
    print("學生總人數", student_count)

    ranked_students = sorted(avg_scores.items(), key=lambda x: x[1], reverse=True) # 將學生成績排序

    # 使用for迴圈將成績單內容印出(20%)
    for i, (student_name, avg_scores) in enumerate(ranked_students, 1):
        print(f"{i}. {student_name}:平均分數{avg_scores:.2f}")

    top_six_students = ranked_students[:6]
    if len(top_six_students) >= 3:
        winners = random.sample(top_six_students, 3) # random為隨機抽取三位
        print("\n中獎學生：")
        # 使用for迴圈將中獎學生的姓名、平均成績印出(15%)
        for i, (student_name, avg_scores) in enumerate(winners, 1):
            print(f"{i}. {student_name}:平均分數{avg_scores:.2f}")

if __name__ == "__main__":
    main()